### ISSUE TITLE
Self-destructing forwarders?

### ISSUE THREAD

**Issue by augustoteixeira** [lorenzb/submarine_sends#1]
Congratulations, this is a really important idea for various applications.

Right now, in the absence of EIP-86, it indeed becomes limited to large transactions (since it involves about $10 just in fees for the 5M gas used to create the forwarders).

Anyway, why didn't you program the forwarder contracts to self destruct after cloning itself? Wouldn't this become gas credit as the transaction proceeds?

**Comment by lorenzb** [comment]
Hi @augustoteixeira,
glad you like it!

> Anyway, why didn't you program the forwarder contracts to self destruct after cloning itself? Wouldn't this become gas credit as the transaction proceeds?

You could indeed program the forwarder contracts (below a certain depth in the tree of forwarder contracts) to self-destruct to save some gas. Since this is an academic prototype, I never implemented this. 

Note that the scheme would still be expensive even with this optimization: self-destructing can at best halve the gas cost of a transaction.

In any case, I have come up with a new scheme for submarine sends that is pretty cheap (on the order of 100k gas) and that works on the Ethereum mainnet today. Details should become public within the next few weeks.

**Comment by augustoteixeira** [comment]
> In any case, I have come up with a new scheme for submarine sends that is pretty cheap (on the order of 100k gas) and that works on the Ethereum mainnet today. Details should become public within the next few weeks.

These are great news! Very much looking forward to seeing this.
